### ISSUE TITLE
locode_db -> locode.db

### ISSUE THREAD

**Issue by 532910** [nspcc-dev/neofs-locode-db#8]
Where the underscore comes from? Let's rename it to `locode.db`!

**Comment by carpawell** [comment]
Where do the dots come from?

**Comment by 532910** [comment]
It happened so.
https://en.wikipedia.org/wiki/Filename_extension
https://en.wikipedia.org/wiki/Media_type#Mime.types
https://wiki.debian.org/MIME/etc/mime.types

**Comment by roman-khimov** [comment]
Obsoleted by #17, there won't be any DB in releases (and IR config).
